### PR TITLE
Add Store + Overlay board

### PR DESCRIPTION
**Pull request by Alipoodle**
Added store + Overlay bug trello boards onto the top bar
If you would like to change the Overlay icon, please do, this seemed like a good icon based upon free Font-Awesome 5.20

Desktop
Mobile

### CODE REVIEW

**Comment by mouse91** [comment]
Looks good 👍 
Though as the boards still seem to be BH-only for some reason, going to hold off on merging until they get made "public"/added to the FAQ on DTesters

**Comment by Alipoodle** [comment]
👌

**Comment by Alipoodle** [comment]
Looks like these are now made a lot more publicly by the addition of each having their own channels now, as well as the boards being mentioned the faqs on the server.

The only one board we're missing is the web one, however I don't see an icon which can easily fit for web within the Free Font Awesome

**Comment by mouse91** [comment]
No worries. Adding the web one will probably need some styling changes since it'll make it an odd number of buttons but I'll look at that later

**Pull request merged**
